### ISSUE TITLE
Private Swarm Multiaddress Issue

### ISSUE THREAD

**Issue by Babramson** [borzunov/health.petals.ml#4]
After updating `INITIAL_PEERS = ` to include the multiaddress of a private swarm `hivemind-dht` non-GPU relay server, i get an this error:
```
Traceback (most recent call last):
  File "/home/sysadmin/anaconda3/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/sysadmin/gitz/health.petals.ml/app.py", line 19, in <module>
    dht = hivemind.DHT(initial_peers=INITIAL_PEERS, client_mode=True, num_workers=32, use_auto_relay=True, start=True)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/hivemind/dht/dht.py", line 88, in __init__
    self.run_in_background(await_ready=await_ready)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/hivemind/dht/dht.py", line 148, in run_in_background
    self.wait_until_ready(timeout)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/hivemind/dht/dht.py", line 151, in wait_until_ready
    self._ready.result(timeout=timeout)
  File "/home/sysadmin/anaconda3/lib/python3.9/site-packages/hivemind/utils/mpfuture.py", line 258, in result
    return super().result(timeout)
  File "/home/sysadmin/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/sysadmin/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
hivemind.p2p.p2p_daemon_bindings.utils.P2PDaemonError: Daemon failed to start: 2023/03/01 09:36:43 failed to parse multiaddr "": empty multiaddr
```

per the instruction, my `INITIAL_PEERS` entry in `app.py` looks like this:
`INITIAL_PEERS = '/ip4/10.148.0.7/tcp/8989/p2p/QmcXhze98AcgGQDDYna23s4Jho96n8wkwLJv78vxtFNq38'`

is there something i'm doing wrong?

**Comment by borzunov** [comment]
Hi @Babramson,

`INITIAL_PEERS` should be a list of strings:

```python
INITIAL_PEERS = ['/ip4/10.148.0.7/tcp/8989/p2p/QmcXhze98AcgGQDDYna23s4Jho96n8wkwLJv78vxtFNq38']
```

I'll add an example to the readme for clarity. Feel free to reopen the issue if you meet any other errors.
